import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Noto_Serif_Bengali } from "next/font/google";
import Header from "@/components/Header";
import Categories from "@/components/Categories";
const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} scroll-smooth`}
    >
      <body>
        <Header/>
        <Categories/>
        <main>{children}</main>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}



// git init
// git add README.md
// git commit -m "first commit"
// git branch -M main
// git remote add origin https://github.com/krishnasaha-30/bazar-dor-app.git
// git push -u origin main
